development:
  adapter: postgresql
  encoding: unicode
  database: cambio_development
  pool: 5
  username: giovannibryden
  password: sk84life

production:
  adapter: postgresql
  encoding: unicode
  host: <%= Rails.application.secrets[:database][:host] %>
  database: <%= Rails.application.secrets[:database][:database] %>
  username: <%= Rails.application.secrets[:database][:username] %>
  port: 5432
  password: <%= Rails.application.secrets[:database][:password] %>