development:
  adapter: postgresql
  encoding: unicode
  database: cambio_development
  pool: 5
  username: <%= ENV['PG_DEV_USERNAME'] %>
  password: <%= ENV['PG_DEV_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PG_HOST'] %>
  database: <%= ENV['PG_DATABASE'] %>
  username: <%= ENV['PG_USERNAME'] %>
  port: 5432
  password: <%= ENV['PG_PASSWORD'] %>