development:
  adapter: postgresql
  encoding: unicode
  database: camb_development
  pool: 5
  username: blog
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: camb_production
  pool: 5
  username: blog
  password:
  host: localhost
