development:
  adapter: postgresql
  encoding: unicode
  database: cambio_development
  pool: 5
  username: giovannibryden
  password: sk84life

production:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PG_HOST'] %>
  database: <%= ENV['PG_DATABASE'] %>
  username: <%= ENV['PG_USERNAME'] %>
  port: 5432
  password: <%= ENV['PG_PASSWORD'] %>